SQL scripts moved to resources and Classpath corrected

diff --git a/src/main/resources/postgres/runSQL b/src/main/resources/postgres/runSQL
--- a/src/main/resources/postgres/runSQL
+++ b/src/main/resources/postgres/runSQL
@@ -8,7 +8,13 @@
 # Author: Denis Lussier.
 # Author: Andres Gomez.
 
-MY_CLASSPATH="../dist/BenchmarkSQL.jar:../lib/postgresql-9.3-1101.jdbc41.jar"
+if [ "${1}" == "" -o "${2}" == "" ] ; then
+ echo "ERROR: Please indicate the properties file and the name of the script file to execute."
+ exit 1
+fi
+BASEDIR=$(dirname "$0")
+
+MY_CLASSPATH="${BASEDIR}/../../BenchmarkSQL.jar:${BASEDIR}/../../lib/*"
 
 MY_PROPERTIES="-Dprop=${1} -DcommandFile=${2}"
 
